### ISSUE TITLE
Does not support Inno version 5.5.00

### ISSUE THREAD

**Issue by hydrian** [onitake/uninno#1]
I just download Ultima 7 Complete (2.0.0.16) from GOG and tried to extract the files for Exult.  I'm using the trunk/master version. I get the following error:

Can't locate Setup/Inno/Struct5500.pm in @INC

**Comment by onitake** [comment]
Interesting. Unless there's a bug hidden somewhere, it means GoG is now using InnoSetup 5.5.
The last time I checked, the Ultima 7 installer was still based on 4.2.

I'll see that all the later versions are supported in the near future.

If you're desperate about playing Ultima, please try one of the other unpacking tools out there or use wine.

**Comment by hydrian** [comment]
After looking around, found that InnoExtract(https://github.com/dscharrer/innoextract.git) supports up to 5.5.0.3.  I'm going give that a try.  I thought I'd let you know so you can determine how the format has changed.

**Comment by onitake** [comment]
I haven't revised uninno in a while, but InnoSetup 5.5 support was implemented some time ago. I just added the deserializer for 5.5.6.
Give it a try if you're interested, or maybe take a look at my Delphi code parser. It makes adding new versions much easier.
