### ISSUE TITLE
Please document the dependencies of this project which are not in core Perl

### ISSUE THREAD

**Issue by ackalker** [onitake/uninno#2]
Using [perlbrew](http://perlbrew.pl/) with a freshly installed perl-5.22.0, I found that I had to install these modules:

```
Switch
DateTime
Data::Hexdumper
Digest::CRC
```

**Comment by onitake** [comment]
Woops, I thought I had documented those.

There's more. You need the command line xz utility installed. And if you have any setup files that use bzip2 or zlib compression, you also need IO::Uncompress::AnyInflate and IO::Uncompress::Bunzip2. If you want to generate new parsers for new IS versions, you also need Marpa::R2.

I'd prefer not having to rely on xz, but none of IO::Uncompress::UnXz nor IO::Uncompress::UnLzma or any of the other LZMA Perl packages allow passing compression parameters or do custom post-processing, last time I checked.

Data::Hexdumper is just used for debugging. I'll remove that.

Switch is required, but the code is still using the deprecated feature 'switch' in some places. I also need to remove all the instances of use constant, it creates more problems than it solves.

**Comment by ackalker** [comment]
Thanks for the quick reply :smile:

**Comment by onitake** [comment]
Uses of Data::Dumper and Data::Hexdump are gone.

The current list of dependencies (aside from Perl 5.10+ builtins) should be:
- Switch
- DateTime
- Digest::CRC
- IO::Uncompress::AnyInflate
- IO::Uncompress::Bunzip2
- xz (command line utility)

I'll update the README later.

**Comment by onitake** [comment]
The README should reflect the dependencies.

I also added a number of updates and fixes, as I noticed that support for older Inno Setup versions was broken. xz is no longer required, but you need Compress::Raw::Lzma now.
